name: Codeception Tests - develop

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"


jobs:
  tests:
    uses: humhub/module-coding-standards/.github/workflows/codeception-develop.yml@main
    with:
      module-id: wiki
      use-rest-module: true
      rest-module-branch: develop
