name: PHP Codeception Tests - v1.11

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-v1.11.yml@main
    with:
      module-id: wiki
      use-rest-module: true